#!/bin/sh

sudo rm -rf /Library/LaunchAgents/com.smiUsbDisplay.macOSInstantView.loginscreen.plist

sudo rm -rf /Applications/macOS\ InstantView.app

sudo cp -rf $HOME/Library/Application\ Support/InstantView/com.smiUsbDisplay.macOSInstantView.loginscreen.plist /Library/LaunchAgents/com.smiUsbDisplay.macOSInstantView.loginscreen.plist

sudo cp -rf ~/Library/Application\ Support/InstantView/macOS\ InstantView.app /Applications/macOS\ InstantView.app
