add_newline = false
command_timeout = 3000
format = """
$username$time$directory$golang$nodejs$python$dart$rust$deno$ruby$cmd_duration$git_status$git_branch
$character"""

[username]
show_always = true
style_user = "bold white"
format = "[$user]($style) "


[character]
success_symbol = "🦄 " 
error_symbol = "🥺 "

[git_status]
style = "bold white"
conflicted = " 🏳"
ahead = " 🏎💨 "
behind =" 😰 "
diverged = " 😵 "
untracked = " 🤷‍ "
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](green)'
renamed = " 👅 "
deleted = " 🗑 "

[gcloud]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[aws]
disabled = true